name: CI Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-et-test:
    runs-on: self-hosted

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t atelier-web .

      - name: Nettoyer un ancien conteneur
        run: docker rm -f mon-site
        continue-on-error: true

      - name: Lancer le conteneur
        run: docker run -d -p 8000:8000 --name mon-site atelier-web

      - name: Tester la page HTML et le CSS
        run: |
          Start-Sleep -Seconds 5
          Invoke-WebRequest -Uri http://localhost:8000/ -UseBasicParsing
          Invoke-WebRequest -Uri http://localhost:8000/style.css -UseBasicParsing

      - name: Afficher les logs en cas d'échec
        if: failure()
        run: docker logs mon-site
